// Platform-neutral gameplay data: tune these values without changing systems.
const GAME_DATA = {
  resource: { startingCoin: 100, drawCost: 50 },
  player: { maxHp: 100 },
  tiers: {
    1: { name:'일반', damage:2, symbol:'●', attackType:'single', colorTier:1 },
    2: { name:'고급', damage:3, symbol:'◆', attackType:'double', colorTier:2 },
    3: { name:'희귀', damage:5, symbol:'■', attackType:'spread', colorTier:3 },
    4: { name:'영웅', damage:12, symbol:'★', attackType:'pierce', colorTier:4 },
    5: { name:'전설', damage:20, symbol:'✦', attackType:'explosion', colorTier:5 },
    6: { name:'신화', damage:35, symbol:'✹', attackType:'chain', colorTier:6 }
  },
  drawRates: [ { tier:1, chance:60 }, { tier:2, chance:22 }, { tier:3, chance:10 }, { tier:4, chance:5 }, { tier:5, chance:2.5 }, { tier:6, chance:.5 } ],
  enemies: { normal: { hp: 10, speed: 90, touchDamage: 5, reward: 50, color: 'normal' } },
  waves: [ { type:'normal', count:5, interval:2.2 }, { type:'normal', count:8, interval:1.9 }, { type:'normal', count:12, interval:1.6 } ]
};
const $ = id => document.getElementById(id);

class ResourceManager { constructor(ui) { this.ui=ui; this.value=0; } reset(){this.value=GAME_DATA.resource.startingCoin;this.render();} canBuy(){return this.value>=GAME_DATA.resource.drawCost;} spend(cost){if(this.value<cost)return false;this.value-=cost;this.render();return true;} add(value){this.value+=value;this.render();} render(){this.ui.resource.textContent=`${this.value} `;const i=document.createElement('i');i.textContent='원';this.ui.resource.append(i);this.ui.buy.disabled=!this.canBuy() || this.ui.boardManager.isFull();} }
class Player { constructor(ui){this.ui=ui;this.hp=100;} reset(){this.hp=GAME_DATA.player.maxHp;this.render();} hurt(amount){this.hp=Math.max(0,this.hp-amount);this.render();return this.hp===0;} render(){this.ui.hp.textContent=`${this.hp} `;const i=document.createElement('i');i.textContent='/ 100';this.ui.hp.append(i);this.ui.hpBar.style.width=`${this.hp}%`;}}
class BoardManager {
  constructor(ui, onAttack){this.ui=ui;this.onAttack=onAttack;this.cells=[];this.pieces=Array(25).fill(null);this.drag=null;this.autoAttackInterval=1;this.autoAttackTimer=0;this.build();}
  build(){this.ui.board.innerHTML='';this.cells=Array.from({length:25},(_,index)=>{const cell=document.createElement('div');cell.className='cell';cell.dataset.index=index;this.ui.board.append(cell);return cell;});}
  reset(){this.pieces.fill(null);this.cells.forEach(c=>c.replaceChildren());this.autoAttackTimer=0;}
  update(dt){this.autoAttackTimer-=dt;if(this.autoAttackTimer>0)return;this.autoAttackTimer=this.autoAttackInterval;this.pieces.forEach(tier=>{if(tier)this.onAttack(tier);});}isFull(){return this.pieces.every(Boolean);} addRandom(){const index=this.pieces.findIndex(v=>v===null);if(index===-1)return false;let roll=Math.random()*100,tier=1;for(const rate of GAME_DATA.drawRates){roll-=rate.chance;if(roll<=0){tier=rate.tier;break;}}this.place(index,tier);return tier;}
  place(index,tier,animate=false){this.pieces[index]=tier;const piece=this.createPiece(index,tier);this.cells[index].replaceChildren(piece);if(animate) piece.classList.add('merge-pop');}
  createPiece(index,tier){const data=GAME_DATA.tiers[tier];const el=document.createElement('div');el.className=`piece tier-${data.colorTier}`;el.dataset.index=index;el.innerHTML=`<span class="symbol">${data.symbol}</span><small>${data.name} · ${data.damage}</small>`;el.addEventListener('pointerdown',e=>this.startPointer(e,index,el));return el;}
  startPointer(e,index,el){if(this.drag)return;e.preventDefault();const r=el.getBoundingClientRect();this.drag={index,el,startX:e.clientX,startY:e.clientY,moved:false,offsetX:e.clientX-r.left,offsetY:e.clientY-r.top};el.setPointerCapture?.(e.pointerId);el.addEventListener('pointermove',this.moveBound=e2=>this.movePointer(e2));el.addEventListener('pointerup',this.endBound=e2=>this.endPointer(e2),{once:true});el.addEventListener('pointercancel',this.endBound,{once:true});}
  movePointer(e){const d=this.drag;if(!d)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(Math.hypot(dx,dy)>7)d.moved=true;if(!d.moved)return;const br=this.ui.board.getBoundingClientRect();if(!d.el.classList.contains('dragging')){d.el.classList.add('dragging');document.body.append(d.el);}d.el.style.width=`${this.cells[0].getBoundingClientRect().width-8}px`;d.el.style.height=`${this.cells[0].getBoundingClientRect().height-8}px`;d.el.style.left=`${e.clientX-br.left-d.offsetX}px`;d.el.style.top=`${e.clientY-br.top-d.offsetY}px`;const target=this.cellAt(e.clientX,e.clientY);this.cells.forEach(c=>c.classList.toggle('drop-target',c===target));}
  endPointer(e){const d=this.drag;if(!d)return;d.el.removeEventListener('pointermove',this.moveBound);this.cells.forEach(c=>c.classList.remove('drop-target'));const target=this.cellAt(e.clientX,e.clientY);if(!d.moved){this.restore(d);}else if(target){this.drop(d.index,Number(target.dataset.index));}else this.restore(d);this.drag=null;}
  cellAt(x,y){return this.cells.find(c=>{const r=c.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;});}
  restore(d){d.el.removeAttribute('style');d.el.classList.remove('dragging');this.cells[d.index].replaceChildren(d.el);}
  drop(from,to){const tier=this.pieces[from], target=this.pieces[to];if(from===to){this.restore(this.drag);return;}if(target===null){this.pieces[from]=null;this.pieces[to]=tier;this.drag.el.remove();this.place(to,tier);return;}if(target===tier){if(tier>=6){this.restore(this.drag);this.ui.message('신화 등급은 더 이상 합칠 수 없습니다.',true);return;}this.pieces[from]=null;this.pieces[to]=null;this.drag.el.remove();this.cells[from].replaceChildren();this.place(to,tier+1,true);this.ui.message(`MERGE! ${GAME_DATA.tiers[tier+1].name} 조각이 생성되었습니다.`);return;}this.restore(this.drag);this.ui.message('서로 다른 등급은 합칠 수 없습니다.',true);}
}
class Enemy { constructor(manager,data){this.manager=manager;this.data=data;this.hp=data.hp;this.x=106;this.dead=false;this.el=document.createElement('div');this.el.className='enemy';this.el.innerHTML='<div class="enemy-hp"><b></b><span></span></div>';manager.ui.enemies.append(this.el);this.render();} update(dt){this.x-=this.data.speed*dt/managerScale(this.manager.ui.battle);if(this.x<=18){this.dead=true;this.el.remove();this.manager.onReach(this.data.touchDamage);return;}this.render();} hit(damage){if(this.dead)return;this.hp-=damage;this.el.classList.add('hit');setTimeout(()=>this.el.classList.remove('hit'),100);this.manager.damagePop(this.x,damage);if(this.hp<=0){this.dead=true;this.el.animate([{transform:'scale(1)'},{transform:'scale(1.6)',opacity:0}],{duration:220}).finished.then(()=>this.el.remove());this.manager.onDeath(this.data.reward);}} render(){this.el.style.left=this.x+'%';const bar=this.el.querySelector('b');bar.style.width=Math.max(0,this.hp/this.data.hp*100)+'%';this.el.querySelector('span').textContent=`${Math.max(0,this.hp)}/${this.data.hp}`;} }
function managerScale(el){return Math.max(1,el.getBoundingClientRect().width/100);}
class EnemyManager { constructor(ui,player,resources){this.ui=ui;this.player=player;this.resources=resources;this.enemies=[];} reset(){this.enemies.forEach(e=>e.el.remove());this.enemies=[];} spawn(type){this.enemies.push(new Enemy(this,GAME_DATA.enemies[type]));} update(dt){this.enemies=this.enemies.filter(e=>!e.dead);this.enemies.forEach(e=>e.update(dt));} closest(excluded=[]){return this.enemies.filter(e=>!e.dead&&!excluded.includes(e)).sort((a,b)=>a.x-b.x)[0];} alive(){return this.enemies.filter(e=>!e.dead).sort((a,b)=>a.x-b.x);} onDeath(reward){this.resources.add(reward);this.ui.message(`몬스터 처치! +${reward}원`);} onReach(damage){if(this.player.hurt(damage))this.ui.game.end();else this.ui.message(`플레이어가 ${damage} 피해를 입었습니다.`,true);} damagePop(x,damage){const p=document.createElement('span');p.className='damage-pop';p.textContent='-'+damage;p.style.left=x+'%';p.style.bottom='42%';this.ui.feedback.append(p);setTimeout(()=>p.remove(),600);} effect(x,label,className=''){const effect=document.createElement('span');effect.className=`combat-effect ${className}`;effect.textContent=label;effect.style.left=x+'%';effect.style.bottom='39%';this.ui.feedback.append(effect);setTimeout(()=>effect.remove(),550);} }
class Projectile { constructor(combat,target,damage,style='single',pierces=0){this.combat=combat;this.target=target;this.damage=damage;this.style=style;this.pierces=pierces;this.hitEnemies=[];this.x=23;this.y=63;this.el=document.createElement('div');this.el.className=`projectile ${style}`;combat.ui.projectiles.append(this.el);this.render();} update(dt){if(this.target.dead){this.nextTarget();if(this.dead)return;}const tx=this.target.x+2,ty=62;const speed=this.style==='pierce'?220:160;const dx=tx-this.x,dy=ty-this.y,dist=Math.hypot(dx,dy);if(dist<3){this.target.hit(this.damage);this.hitEnemies.push(this.target);if(this.pierces>0){this.pierces--;this.nextTarget();}else this.remove();return;}this.x+=dx/dist*speed*dt/managerScale(this.combat.ui.battle);this.y+=dy/dist*speed*dt/managerScale(this.combat.ui.battle);this.render();} nextTarget(){const next=this.combat.enemies.closest(this.hitEnemies);if(next)this.target=next;else this.remove();} render(){this.el.style.left=this.x+'%';this.el.style.top=this.y+'%';} remove(){this.dead=true;this.el.remove();} }
class CombatSystem { constructor(ui,enemies){this.ui=ui;this.enemies=enemies;this.projectiles=[];} fire(target,damage,style,pierces=0){if(target)this.projectiles.push(new Projectile(this,target,damage,style,pierces));} attack(tier){const target=this.enemies.closest();if(!target){this.ui.message('공격할 몬스터가 없습니다.');return;}const data=GAME_DATA.tiers[tier];this.ui.player.classList.remove('attacking');void this.ui.player.offsetWidth;this.ui.player.classList.add('attacking');if(data.attackType==='single')this.fire(target,data.damage,'single');if(data.attackType==='double')for(let i=0;i<2;i++)setTimeout(()=>this.fire(this.enemies.closest(),data.damage,'double'),i*100);if(data.attackType==='spread')for(let i=0;i<3;i++)setTimeout(()=>this.fire(this.enemies.closest(),data.damage,'spread'),i*55);if(data.attackType==='pierce')this.fire(target,data.damage,'pierce',2);if(data.attackType==='explosion')this.fire(target,data.damage,'explosion');if(data.attackType==='chain')this.chain(data.damage);this.ui.message(`${data.name} · ${this.attackName(data.attackType)}`);} attackName(type){return ({single:'단발 사격',double:'2연사',spread:'산탄 3발',pierce:'관통탄',explosion:'폭발탄',chain:'연쇄 번개'})[type];} chain(damage){this.enemies.alive().slice(0,3).forEach((enemy,index)=>setTimeout(()=>{if(enemy.dead)return;enemy.hit(Math.round(damage/(index+1)));this.enemies.effect(enemy.x,'⚡','lightning');},index*120));} explode(target,damage){this.enemies.alive().filter(enemy=>Math.abs(enemy.x-target.x)<18).forEach(enemy=>enemy.hit(damage));this.enemies.effect(target.x,'✹','explosion-effect');} update(dt){this.projectiles=this.projectiles.filter(p=>!p.dead);this.projectiles.forEach(p=>{const wasAlive=!p.dead;p.update(dt);if(wasAlive&&p.dead&&p.style==='explosion')this.explode(p.target,p.damage);});} reset(){this.projectiles.forEach(p=>p.remove());this.projectiles=[];} }
class WaveManager { constructor(ui,enemies){this.ui=ui;this.enemies=enemies;this.wave=1;this.spawned=0;this.timer=2;this.done=false;} reset(){this.wave=1;this.spawned=0;this.timer=2;this.done=false;this.render();} update(dt){const data=GAME_DATA.waves[Math.min(this.wave-1,GAME_DATA.waves.length-1)];this.timer-=dt;if(this.spawned<data.count&&this.timer<=0){this.enemies.spawn(data.type);this.spawned++;this.timer=data.interval;}if(this.spawned===data.count&&this.enemies.enemies.length===0&&!this.done){this.done=true;this.timer=2;this.ui.message(`Wave ${this.wave} 클리어! 다음 적이 접근합니다.`);}if(this.done&&this.timer<=0){this.wave++;this.spawned=0;this.done=false;this.timer=.5;this.render();}} render(){this.ui.wave.textContent=this.wave;} }
class UIManager { constructor(){this.resource=$('resourceValue');this.hp=$('playerHpValue');this.hpBar=$('playerHpBar');this.wave=$('waveValue');this.board=$('board');this.buy=$('buyButton');this.messageEl=$('statusMessage');this.enemies=$('enemyLayer');this.projectiles=$('projectileLayer');this.feedback=$('battleFeedback');this.battle=$('battlefield');this.player=$('player');this.gameOver=$('gameOver');this.startScreen=$('startScreen');} message(text,warn=false){this.messageEl.textContent=text;this.messageEl.classList.toggle('warn',warn);} }
class GameManager { constructor(){this.ui=new UIManager();this.resources=new ResourceManager(this.ui);this.player=new Player(this.ui);this.enemies=new EnemyManager(this.ui,this.player,this.resources);this.combat=new CombatSystem(this.ui,this.enemies);this.board=new BoardManager(this.ui,t=>this.combat.attack(t));this.ui.boardManager=this.board;this.waves=new WaveManager(this.ui,this.enemies);this.ui.game=this;this.ui.buy.addEventListener('click',()=>this.buy());$('startButton').addEventListener('click',()=>this.start());$('restartButton').addEventListener('click',()=>this.restart());this.running=false;this.last=performance.now();this.resetState();requestAnimationFrame(t=>this.loop(t));} resetState(){this.running=false;this.ui.gameOver.hidden=true;this.resources.reset();this.player.reset();this.board.reset();this.enemies.reset();this.combat.reset();this.waves.reset();this.last=performance.now();this.ui.message('GAME START를 눌러 방어를 시작하세요.');} start(){this.ui.startScreen.hidden=true;this.last=performance.now();this.running=true;this.ui.message('방어 시작! 50원으로 퍼즐 조각을 뽑으세요.');} restart(){this.resetState();this.ui.startScreen.hidden=false;} buy(){if(!this.running)return;if(this.board.isFull()){this.ui.message('퍼즐판이 가득 찼습니다. 조각을 합쳐 공간을 만드세요.',true);return;}if(!this.resources.spend(GAME_DATA.resource.drawCost)){this.ui.message('코인이 부족합니다. 뽑기에는 50원이 필요합니다.',true);return;}const tier=this.board.addRandom();this.ui.message(`${GAME_DATA.tiers[tier].name} 조각을 뽑았습니다!`);this.resources.render();} end(){if(!this.running)return;this.running=false;this.ui.gameOver.hidden=false;$('finalWave').textContent=`최종 Wave ${this.waves.wave}`;} loop(now){const dt=Math.min(.05,(now-this.last)/1000);this.last=now;if(this.running){this.board.update(dt);this.enemies.update(dt);this.combat.update(dt);this.waves.update(dt);}requestAnimationFrame(t=>this.loop(t));} }
new GameManager();
